import type { Project, SkillCategory, TimelineItem } from '@/types';

export const fallbackProjects: Project[] = [
  {
    id: '9',
    title: 'Statistical Sales Analysis',
    slug: 'statistical-sales-analysis',
    description:
      'Analisis estadistico de factores asociados a ingresos por ventas con Python, regresion lineal multiple, metricas de evaluacion y diagnostico estadistico.',
    long_description:
      'Proyecto finalizado del Master en Data Science basado en un dataset sintetico de 60.000 observaciones y 23 variables. Estudia asociaciones entre marketing, comportamiento del cliente, engagement digital y contexto comercial con sales_revenue_usd, usando EDA, deteccion de outliers, seleccion de variables, regresion lineal multiple, R2, MAE, RMSE, VIF, diagnostico de residuos, test de White y errores robustos HC3.',
    categories: ['master', 'data-analytics'],
    technologies: ['Python', 'Statistics', 'Regression', 'Pandas'],
    image_url: '/images/projects/statistical-sales-analysis.jpg',
    status: 'terminado',
    featured: true,
    learnings: [
      'Analisis estadistico observacional',
      'Regresion lineal multiple e interpretacion ceteris paribus',
      'Diagnostico con VIF, residuos, White test y HC3',
      'Comunicacion de insights sin asumir causalidad',
    ],
    created_at: '2026-09-01',
  },
  {
    id: '10',
    title: 'Global Electronics Retail Analytics',
    slug: 'global-electronics-powerbi',
    description:
      'Dashboard completo de Business Intelligence en Power BI con Power Query, modelo estrella, DAX, KPIs, navegacion, filtros y storytelling visual.',
    long_description:
      'Proyecto finalizado del Master en Data Science sobre Global Electronics Retailer. Construye un informe ejecutivo e interactivo con preparacion de datos en Power Query, modelo en estrella, calendario DAX, medidas de ventas, margen, pedidos, ticket medio, YoY, YTD y rankings, ademas de paginas de resumen, productos, clientes, mercados, tiendas y detalle.',
    categories: ['master', 'data-analytics'],
    technologies: ['Power BI', 'Power Query', 'DAX', 'Data Modeling'],
    image_url: '/images/projects/global-electronics-powerbi.jpg',
    status: 'terminado',
    featured: true,
    learnings: [
      'Flujo completo de Business Intelligence',
      'Power Query y modelado en estrella',
      'Medidas DAX, KPIs e inteligencia temporal',
      'Storytelling visual con filtros, bookmarks y drillthrough',
    ],
    created_at: '2026-09-01',
  },
  {
    id: '8',
    title: 'AI Marketing Intelligence Platform',
    slug: 'marketing-ia',
    description:
      'Plataforma enterprise de inteligencia de marketing con sistema multiagente LangGraph, RAG, ML clasico, FastAPI y dashboard Next.js.',
    long_description:
      'Proyecto en progreso que convierte datos transaccionales de ecommerce en recomendaciones de negocio. Combina scoring RFM, clustering KMeans, prediccion de churn, simulacion de campanas, recuperacion RAG con Qdrant y agentes especializados capaces de razonar sobre KPIs, segmentos, playbooks CRM y ROI estimado. Funciona con Ollama local, OpenAI o modo mock.',
    categories: ['data-analytics', 'data-science'],
    technologies: ['LangGraph', 'FastAPI', 'Ollama', 'Qdrant', 'RAG', 'Next.js', 'TypeScript', 'scikit-learn'],
    github_url: 'https://github.com/danielgarciaN/marketing-ia',
    image_url: '/images/projects/marketing-ia.jpg',
    status: 'en_proceso',
    featured: true,
    learnings: [
      'Orquestacion multiagente con LangGraph',
      'RAG con Qdrant y embeddings locales',
      'APIs de analitica y simulacion de campanas',
      'Arquitectura AI Engineering con valor de negocio',
    ],
    created_at: '2026-05-20',
  },
  {
    id: '1',
    title: 'Expected Goals xG - StatsBomb',
    slug: 'expected-goals-xg-statsbomb',
    description:
      'Notebook de nivel máster para construir un modelo de Expected Goals con datos abiertos de StatsBomb, storytelling y evaluación avanzada.',
    long_description:
      'Proyecto finalizado centrado en crear una notebook entregable de Data Science aplicada al fútbol. El objetivo es modelar la probabilidad de que un tiro acabe en gol mediante Logistic Regression, Random Forest y XGBoost, incorporando feature engineering futbolístico, calibración, comparación con xG de StatsBomb e insights interpretables.',
    categories: ['master', 'data-analytics'],
    technologies: ['Python', 'StatsBomb', 'Pandas', 'scikit-learn', 'XGBoost', 'Matplotlib', 'Seaborn'],
    image_url: '/images/projects/expected-goals-xg-statsbomb.jpg',
    status: 'terminado',
    featured: true,
    learnings: [
      'Modelado de Expected Goals',
      'Feature engineering futbolístico',
      'Evaluación con ROC-AUC, Brier Score y calibración',
      'Storytelling con datos deportivos',
    ],
    created_at: '2026-05-01',
  },
  {
    id: '2',
    title: 'TFG - Modulo de Chatbots',
    slug: 'tfg-modulo-chatbots',
    description:
      'Proyecto de Trabajo Final de Grado centrado en el diseno y desarrollo de un modulo de agentes conversacionales/chatbots.',
    long_description:
      'Trabajo de Fin de Grado desarrollado en colaboración con Catalana Occident. El proyecto diseña una arquitectura de agentes conversacionales configurables, con flujos gestionados mediante estructuras clave-valor, validación mediante Proof of Concept e integración con IA generativa para asistir procesos de soporte e incidencias.',
    categories: ['universidad'],
    technologies: ['IA generativa', 'Arquitectura software', 'SQL', 'C#', '.NET', 'PoC'],
    image_url: '/images/projects/tfg-agentes-conversacionales-iatech.jpg',
    status: 'terminado',
    featured: true,
    learnings: [
      'Diseño de arquitecturas parametrizables',
      'Validación de soluciones mediante Proof of Concept',
      'Aplicación de IA generativa a procesos corporativos',
      'Modelado de flujos conversacionales configurables',
    ],
    created_at: '2025-06-01',
  },
  {
    id: '3',
    title: 'FindIt',
    slug: 'find-it',
    description:
      'Backend serverless para un juego de retos visuales, validando fotografías de objetos con Google Cloud Vision y Firebase.',
    long_description:
      'Aplicación gamificada con foco backend que combina Firebase, Cloud Functions y Google Cloud Vision API. El usuario recibe un reto aleatorio, fotografía el objeto y el sistema valida automáticamente si coincide. Incluye modos de juego, puntuación y ranking.',
    categories: ['universidad', 'backend'],
    technologies: ['TypeScript', 'Firebase', 'Cloud Functions', 'Google Cloud Vision API', 'Backend'],
    github_url: 'https://github.com/danielgarciaN/find-it',
    image_url: '/images/projects/find-it.jpg',
    status: 'terminado',
    featured: true,
    learnings: [
      'Integración con Google Cloud Vision API',
      'Arquitectura serverless con Firebase',
      'Validación backend de retos visuales',
    ],
    created_at: '2024-12-01',
  },
  {
    id: '4',
    title: 'LoL Win Prediction',
    slug: 'lol-win-prediction',
    description:
      'Modelo de machine learning para predecir el equipo ganador en partidas de League of Legends usando datos reales.',
    long_description:
      'Proyecto de Data Science que construye un modelo predictivo con XGBoost para estimar el ganador de una partida. Incluye feature engineering, control de data leakage, entrenamiento con scikit-learn y análisis de resultados orientado a explicabilidad.',
    categories: ['universidad', 'data-science'],
    technologies: ['Python', 'Pandas', 'scikit-learn', 'XGBoost', 'Matplotlib', 'Jupyter'],
    github_url: 'https://github.com/danielgarciaN/lol-win-prediction',
    image_url: '/images/projects/lol-win-prediction.jpg',
    status: 'terminado',
    featured: true,
    learnings: [
      'Feature engineering aplicado a datos competitivos',
      'Prevención de data leakage',
      'Evaluación de modelos predictivos',
      'Interpretación de métricas y errores',
    ],
    created_at: '2025-01-15',
  },
  {
    id: '5',
    title: 'FutbolData',
    slug: 'futbol-data',
    description:
      'Scripts de análisis y visualización de datos de fútbol: mapas de calor, redes de pases, posesión y valoración de jugadores.',
    long_description:
      'Repositorio de análisis deportivo con Python orientado a transformar datos de eventos y tracking en visualizaciones útiles para interpretación táctica. Incluye mapas de calor, grafos de pases y métricas de rendimiento.',
    categories: ['data-analytics', 'data-science'],
    technologies: ['Python', 'Pandas', 'Matplotlib', 'Data Analysis'],
    github_url: 'https://github.com/danielgarciaN/futbol-data',
    image_url: '/images/projects/futbol-data.jpg',
    status: 'terminado',
    featured: true,
    learnings: [
      'Procesamiento de datos deportivos',
      'Visualización avanzada con Matplotlib',
      'Análisis estadístico aplicado al fútbol',
    ],
    created_at: '2024-11-01',
  },
  {
    id: '6',
    title: 'Tofu Awards',
    slug: 'tofu-awards',
    description:
      'Aplicación web para gestionar y votar premios, desplegada con Firebase Hosting y CI/CD con GitHub Actions.',
    long_description:
      'Proyecto web con frontend en JavaScript, CSS y HTML, desplegado en Firebase Hosting con pipeline automatizado mediante GitHub Actions. Permite gestionar categorías y sistema de votación.',
    categories: ['web-app'],
    technologies: ['JavaScript', 'CSS', 'HTML', 'Firebase', 'GitHub Actions'],
    github_url: 'https://github.com/danielgarciaN/tofu-awards',
    image_url: '/images/projects/tofu-awards.jpg',
    status: 'terminado',
    featured: false,
    learnings: [
      'Despliegue con Firebase Hosting',
      'Automatización con GitHub Actions',
      'Desarrollo frontend con JavaScript vanilla',
    ],
    created_at: '2024-06-01',
  },
  {
    id: '7',
    title: 'UNImate',
    slug: 'unimate',
    description:
      'Proyecto colaborativo académico para facilitar la organización académica y la conexión dentro de la comunidad universitaria.',
    long_description:
      'Aplicación desarrollada en equipo, orientada a mejorar la experiencia académica mediante herramientas de organización, colaboración y gestión de tareas.',
    categories: ['universidad', 'web-app'],
    technologies: ['React', 'Node.js', 'Firebase', 'CSS', 'Trabajo en equipo'],
    github_url: 'https://github.com/danielgarciaN/Unimate',
    image_url: '/images/projects/unimate.JPG',
    status: 'terminado',
    featured: false,
    learnings: [
      'Trabajo con repositorio compartido',
      'Diseño centrado en comunidad universitaria',
      'Integración de servicios cloud',
    ],
    created_at: '2024-03-01',
  },
];

export const skillCategories: SkillCategory[] = [
  {
    name: 'Data Analytics',
    icon: 'bar-chart',
    skills: [
      { id: 's1', name: 'SQL', category: 'Data Analytics', order_index: 0 },
      { id: 's2', name: 'Power BI', category: 'Data Analytics', order_index: 1 },
      { id: 's3', name: 'Power Query', category: 'Data Analytics', order_index: 2 },
      { id: 's4', name: 'DAX', category: 'Data Analytics', order_index: 3 },
      { id: 's5', name: 'Data Visualization', category: 'Data Analytics', order_index: 4 },
      { id: 's6', name: 'Data Modeling', category: 'Data Analytics', order_index: 5 },
      { id: 's7', name: 'Statistics', category: 'Data Analytics', order_index: 6 },
      { id: 's8', name: 'Exploratory Data Analysis', category: 'Data Analytics', order_index: 7 },
      { id: 's9', name: 'Business Intelligence', category: 'Data Analytics', order_index: 8 },
      { id: 's10', name: 'KPI Analysis', category: 'Data Analytics', order_index: 9 },
    ],
  },
  {
    name: 'Data Engineering / Cloud',
    icon: 'database',
    skills: [
      { id: 's11', name: 'Snowflake', category: 'Data Engineering / Cloud', order_index: 0 },
      { id: 's12', name: 'ETL / ELT', category: 'Data Engineering / Cloud', order_index: 1 },
      { id: 's13', name: 'Data Warehousing', category: 'Data Engineering / Cloud', order_index: 2 },
      { id: 's14', name: 'Relational Databases', category: 'Data Engineering / Cloud', order_index: 3 },
      { id: 's15', name: 'Data Transformation', category: 'Data Engineering / Cloud', order_index: 4 },
      { id: 's16', name: 'SQL', category: 'Data Engineering / Cloud', order_index: 5 },
    ],
  },
  {
    name: 'Data Science / AI',
    icon: 'brain',
    skills: [
      { id: 's17', name: 'Python', category: 'Data Science / AI', order_index: 0 },
      { id: 's18', name: 'Pandas', category: 'Data Science / AI', order_index: 1 },
      { id: 's19', name: 'NumPy', category: 'Data Science / AI', order_index: 2 },
      { id: 's20', name: 'scikit-learn', category: 'Data Science / AI', order_index: 3 },
      { id: 's21', name: 'Machine Learning', category: 'Data Science / AI', order_index: 4 },
      { id: 's22', name: 'Artificial Intelligence', category: 'Data Science / AI', order_index: 5 },
      { id: 's23', name: 'XGBoost', category: 'Data Science / AI', order_index: 6 },
      { id: 's24', name: 'Statsmodels', category: 'Data Science / AI', order_index: 7 },
    ],
  },
  {
    name: 'Software Engineering',
    icon: 'server',
    skills: [
      { id: 's25', name: 'C#', category: 'Software Engineering', order_index: 0 },
      { id: 's26', name: '.NET', category: 'Software Engineering', order_index: 1 },
      { id: 's27', name: 'Java', category: 'Software Engineering', order_index: 2 },
      { id: 's28', name: 'TypeScript', category: 'Software Engineering', order_index: 3 },
      { id: 's29', name: 'JavaScript', category: 'Software Engineering', order_index: 4 },
      { id: 's30', name: 'APIs REST', category: 'Software Engineering', order_index: 5 },
      { id: 's31', name: 'Backend Development', category: 'Software Engineering', order_index: 6 },
      { id: 's32', name: 'Software Architecture', category: 'Software Engineering', order_index: 7 },
    ],
  },
  {
    name: 'Frontend & Cloud',
    icon: 'globe',
    skills: [
      { id: 's33', name: 'React', category: 'Frontend & Cloud', order_index: 0 },
      { id: 's34', name: 'Next.js', category: 'Frontend & Cloud', order_index: 1 },
      { id: 's35', name: 'Tailwind CSS', category: 'Frontend & Cloud', order_index: 2 },
      { id: 's36', name: 'Firebase', category: 'Frontend & Cloud', order_index: 3 },
      { id: 's37', name: 'Google Cloud', category: 'Frontend & Cloud', order_index: 4 },
      { id: 's38', name: 'Supabase', category: 'Frontend & Cloud', order_index: 5 },
      { id: 's39', name: 'Docker', category: 'Frontend & Cloud', order_index: 6 },
    ],
  },
  {
    name: 'Herramientas & Metodologías',
    icon: 'wrench',
    skills: [
      { id: 's40', name: 'Git', category: 'Herramientas & Metodologías', order_index: 0 },
      { id: 's41', name: 'GitHub', category: 'Herramientas & Metodologías', order_index: 1 },
      { id: 's42', name: 'JIRA', category: 'Herramientas & Metodologías', order_index: 2 },
      { id: 's43', name: 'Scrum', category: 'Herramientas & Metodologías', order_index: 3 },
      { id: 's44', name: 'Kanban', category: 'Herramientas & Metodologías', order_index: 4 },
      { id: 's45', name: 'Documentación técnica', category: 'Herramientas & Metodologías', order_index: 5 },
      { id: 's46', name: 'Testing', category: 'Herramientas & Metodologías', order_index: 6 },
      { id: 's47', name: 'Debugging', category: 'Herramientas & Metodologías', order_index: 7 },
    ],
  },
  {
    name: 'Habilidades humanas',
    icon: 'users',
    skills: [
      { id: 's48', name: 'Trabajo en equipo', category: 'Habilidades humanas', order_index: 0 },
      { id: 's49', name: 'Comunicación clara', category: 'Habilidades humanas', order_index: 1 },
      { id: 's50', name: 'Adaptabilidad', category: 'Habilidades humanas', order_index: 2 },
      { id: 's51', name: 'Resolución de problemas', category: 'Habilidades humanas', order_index: 3 },
      { id: 's52', name: 'Liderazgo', category: 'Habilidades humanas', order_index: 4 },
      { id: 's53', name: 'Pensamiento crítico', category: 'Habilidades humanas', order_index: 5 },
      { id: 's54', name: 'Proactividad', category: 'Habilidades humanas', order_index: 6 },
      { id: 's55', name: 'Aprendizaje rápido', category: 'Habilidades humanas', order_index: 7 },
    ],
  },
  {
    name: 'Idiomas',
    icon: 'languages',
    skills: [
      { id: 's56', name: 'Español nativo', category: 'Idiomas', order_index: 0 },
      { id: 's57', name: 'Catalán nativo', category: 'Idiomas', order_index: 1 },
      { id: 's58', name: 'Inglés medio', category: 'Idiomas', order_index: 2 },
    ],
  },
];

export const timelineItems: TimelineItem[] = [
  {
    id: 't0',
    type: 'work',
    title: 'Data Analyst',
    organization: 'SDG Group',
    location: 'España',
    start_date: '2026-09',
    current: true,
    description:
      'Analista de Datos en SDG Group, consultora especializada en Data, Analytics e Inteligencia Artificial. Participo en proyectos de consultoría relacionados con análisis, transformación y visualización de datos y soluciones orientadas a negocio. Proyecto actual: Fundación "la Caixa".',
    highlights: ['Data Analyst', 'Full-time', 'Permanent', 'Analytics', 'Data Transformation', 'Data Visualization'],
    order_index: 0,
  },
  {
    id: 't1',
    type: 'work',
    title: 'Software Developer - Arquitectura, IA y procesos',
    organization: 'Grupo Catalana Occident / Occident',
    location: 'España',
    start_date: '2024-10',
    end_date: '2026-05',
    current: false,
    description:
      'Desarrollo y mejora del módulo corporativo IATeach, una solución orientada a IA para gestión documental y procesos internos. Experiencia en arquitectura corporativa, lógica de negocio con C#/.NET, integración SQL, interfaces GAAN, validaciones JavaScript y trabajo ágil con JIRA, aportando criterio técnico en un entorno real de producto, datos y automatización.',
    highlights: ['AI Engineering', 'C#', '.NET', 'SQL', 'JavaScript', 'GAAN', 'JIRA', 'Arquitectura'],
    order_index: 1,
  },
  {
    id: 't2',
    type: 'education',
    title: 'Máster Evolve - Data Science / Inteligencia Artificial',
    organization: 'Evolve',
    start_date: '2026-03',
    current: true,
    description:
      'Máster de Evolve orientado a entorno profesional real. Especialización en Python, SQL, Power BI, análisis avanzado de datos, automatización, machine learning y toma de decisiones basada en datos.',
    highlights: ['Python', 'SQL', 'Power BI', 'Data Science', 'Machine Learning', 'AI'],
    order_index: 2,
  },
  {
    id: 't3',
    type: 'education',
    title: 'Ingeniería Informática - Mención en Ingeniería del Software',
    organization: 'Formación universitaria',
    start_date: '2020-09',
    end_date: '2025-06',
    current: false,
    description:
      'Grado en Ingeniería Informática con formación integral en ingeniería del software, bases de datos, algoritmos, sistemas, desarrollo web y proyectos en equipo. Trabajo final centrado en agentes conversacionales e IA generativa aplicado a un contexto corporativo.',
    highlights: ['Ingeniería del Software', 'Bases de datos', 'Algoritmos', 'TFG IA', 'Trabajo en equipo'],
    order_index: 3,
  },
  {
    id: 't4',
    type: 'certification',
    title: 'Proyectos de AI Engineering y Data Science',
    organization: 'GitHub personal',
    start_date: '2023-01',
    current: true,
    description:
      'Desarrollo de proyectos propios en Python, análisis de datos, ML, RAG, agentes, aplicaciones web y cloud. Enfoque práctico en documentación, arquitectura limpia y construcción de soluciones con utilidad real.',
    highlights: ['AI Engineering', 'Data Science', 'RAG', 'Agentes', 'Machine Learning', 'Cloud'],
    order_index: 4,
  },
];

export const personalInfo = {
  name: 'Daniel García Nilo',
  shortName: 'Daniel García',
  title: 'Data Analyst & Computer Engineer',
  bio: 'Data Analyst e ingeniero informático con background en Software Engineering, Data Science e Inteligencia Artificial. Combino analítica, visualización, estadística, BI y tecnología para convertir datos en insights útiles para negocio.',
  email: 'danielgarcianilo1@gmail.com',
  phone: '+34 644 41 01 49',
  github: 'https://github.com/danielgarciaN',
  linkedin: 'https://www.linkedin.com/in/danielgarcianilo/',
  location: 'España',
  profileImage: '/images/profile/daniel-garcia-nilo.jpg',
  cvUrl: '/cv/daniel-garcia-nilo-cv.pdf',
};
